vim.diagnostic.config({ virtual_text = false }) -- tiny-inline diag.
vim.g.editorconfig = false
local opt = vim.opt
vim.opt.textwidth = 90
vim.opt.formatoptions:append("t")
opt.backup = false
opt.cmdheight = 0
opt.confirm = true
vim.g.wrapmargin = 0
opt.expandtab = true
opt.fillchars:append({ eob = " " })
opt.grepprg = "rg --vimgrep"
opt.ignorecase = true
opt.laststatus = 3
opt.mouse = "a"
opt.number = true
opt.pumheight = 10
opt.relativenumber = true
opt.scrolloff = 8
opt.shiftwidth = 4
opt.showcmd = true
opt.showcmdloc = "statusline"
opt.showmode = false
opt.showtabline = 1
opt.sidescroll = 3
opt.sidescrolloff = 3
opt.signcolumn = "yes"
opt.smartcase = true
opt.smartindent = true
opt.spell = false
opt.spelllang = "en_us"
opt.spelloptions = "camel"
opt.splitbelow = true
opt.splitkeep = "screen"
opt.splitright = true
opt.swapfile = false
opt.tabstop = 4
opt.timeoutlen = 800
opt.undofile = true
opt.undolevels = 10000
opt.updatetime = 200
opt.virtualedit = "block"
opt.guicursor = "n-v-c-i:block"

vim.g.snacks_animate = false
vim.opt.list = true
vim.opt.listchars = {
  lead = "·",
  trail = "•",
  multispace = "∅",
  nbsp = "‡",
  tab = "⇥»",
  precedes = "❮",
  extends = "❯",
  -- eol = "↵",
}
